# Generated by Django 3.2.25 on 2024-06-25 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20240625_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingedients',
            new_name='ingredients',
        ),
    ]
